/* Replace with your SQL commands */

CREATE TABLE `tblwallettransaction` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idApp` int(11) DEFAULT NULL,
  `Amount` decimal(18,2) DEFAULT NULL,
  `Type` varchar(100) DEFAULT NULL,
  `Remark` text,
  `OrderNumber` varchar(200) DEFAULT NULL,
  `Country` varchar(500) DEFAULT NULL,
  `PaymentType` varchar(200) DEFAULT NULL,
  `DeviceId` varchar(500) DEFAULT NULL,
  `IsPaymentSuccess` int(11) DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  `CreatedBy` varchar(100) DEFAULT NULL,
  `ExpiryDate` datetime DEFAULT NULL,
  `ModifiedDate` datetime DEFAULT NULL,
  `ModifiedBy` varchar(100) DEFAULT NULL,
  `PaymentReceipt` text,
  PRIMARY KEY (`id`),
  KEY `FK_tblwallTran_tblappinfo_idx` (`idApp`),
  CONSTRAINT `FK_tblwallTran_tblappinfo` FOREIGN KEY (`idApp`) REFERENCES `tblappinfo` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `tblwallet` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idwalletTransaction` int(11) DEFAULT NULL,
  `Amount` decimal(18,2) DEFAULT NULL,
  `Type` varchar(50) DEFAULT NULL,
  `Remark` text,
  `Createdby` varchar(50) DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_tblwallettrans_tblwallets_idx` (`idwalletTransaction`),
  CONSTRAINT `FK_tblwallettrans_tblwallets` FOREIGN KEY (`idwalletTransaction`) REFERENCES `tblwallettransaction` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `tblorderservicestatus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `OrderStatus` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `tblorderservicestatus` (`OrderStatus`) VALUES ('Pending');
INSERT INTO `tblorderservicestatus` (`OrderStatus`) VALUES ('Approved');
INSERT INTO `tblorderservicestatus` (`OrderStatus`) VALUES ('Completed');

alter table `tblsimdetails` ADD COLUMN `idApp` INT(11) NULL AFTER `idTelCo`;


CREATE TABLE `tblorderservice` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `CustomerId` int(11) DEFAULT NULL,
  `CustomerPO` varchar(50) DEFAULT NULL,
  `BillingAddressId` int(11) DEFAULT NULL,
  `ShippFirstName` varchar(50) DEFAULT NULL,
  `ShippLastName` varchar(50) DEFAULT NULL,
  `ShippAddress1` longtext,
  `ShippAddress2` longtext,
  `ShippidCountry` int(11) DEFAULT NULL,
  `ShippidState` int(11) DEFAULT NULL,
  `ShippidCity` varchar(255) DEFAULT NULL,
  `ShippPostCode` varchar(10) DEFAULT NULL,
  `ShippCompanyName` varchar(255) DEFAULT NULL,
  `OrderNotes` longtext,
  `OrderStatusId` int(11) DEFAULT NULL,
  `ImageUrl` varchar(255) DEFAULT NULL,
  `ShippingStatusId` int(11) DEFAULT NULL,
  `PaymentStatusId` int(11) DEFAULT NULL,
  `PaymentMethodSystemName` varchar(250) DEFAULT NULL,
  `CustomerCurrencyCode` varchar(50) DEFAULT NULL,
  `CurrencyRate` decimal(16,2) DEFAULT NULL,
  `CustomerTaxDisplayTypeId` int(11) DEFAULT NULL,
  `VatNumber` varchar(50) DEFAULT NULL,
  `OrderSubtotalInclTax` decimal(16,2) DEFAULT NULL,
  `OrderSubtotalExclTax` decimal(16,2) DEFAULT NULL,
  `OrderSubTotalDiscountInclTax` decimal(16,2) DEFAULT NULL,
  `OrderSubTotalDiscountExclTax` decimal(16,2) DEFAULT NULL,
  `OrderShippingInclTax` decimal(16,2) DEFAULT NULL,
  `OrderShippingExclTax` decimal(16,2) DEFAULT NULL,
  `PaymentMethodAdditionalFeeInclTax` decimal(16,2) DEFAULT NULL,
  `PaymentMethodAdditionalFeeExclTax` decimal(16,2) DEFAULT NULL,
  `TaxRates` decimal(16,2) DEFAULT NULL,
  `OrderTax` decimal(16,2) DEFAULT NULL,
  `OrderDiscount` decimal(16,2) DEFAULT NULL,
  `OrderTotal` decimal(16,2) DEFAULT NULL,
  `RefundedAmount` decimal(16,2) DEFAULT NULL,
  `RewardPointsWereAdded` int(11) DEFAULT NULL,
  `CheckoutAttributeDescription` varchar(500) DEFAULT NULL,
  `CheckoutAttributesXml` longtext,
  `CustomerLanguageId` int(11) DEFAULT NULL,
  `AffiliateId` int(11) DEFAULT NULL,
  `CustomerIp` varchar(50) DEFAULT NULL,
  `AllowStoringCreditCardNumber` tinyint(1) DEFAULT NULL,
  `CardType` varchar(50) DEFAULT NULL,
  `CardName` varchar(50) DEFAULT NULL,
  `CardNumber` varchar(50) DEFAULT NULL,
  `MaskedCreditCardNumber` varchar(50) DEFAULT NULL,
  `CardCvv2` int(11) DEFAULT NULL,
  `CardExpirationMonth` int(11) DEFAULT NULL,
  `CardExpirationyear` int(11) DEFAULT NULL,
  `AuthorizationTransactionId` int(11) DEFAULT NULL,
  `AuthorizationTransactionCode` varchar(50) DEFAULT NULL,
  `AuthorizationTransactionResult` varchar(50) DEFAULT NULL,
  `CaptureTransactionId` int(11) DEFAULT NULL,
  `CaptureTransactionResult` varchar(50) DEFAULT NULL,
  `SubscriptionTransactionId` int(11) DEFAULT NULL,
  `PurchaseOrderNumber` varchar(50) DEFAULT NULL,
  `PaidDateUtc` datetime DEFAULT NULL,
  `ShippingMethod` varchar(50) DEFAULT NULL,
  `ShippingRateComputationMethodSystemName` varchar(50) DEFAULT NULL,
  `Courier` varchar(255) DEFAULT NULL,
  `TrackingNumber` varchar(50) DEFAULT NULL,
  `CustomValuesXml` longtext,
  `Deleted` tinyint(1) DEFAULT NULL,
  `Terms` longtext,
  `CreatedBy` varchar(255) DEFAULT NULL,
  `CreatedOnUtc` datetime NOT NULL,
  `AuthorizeWorkId` int(11) DEFAULT NULL,
  `ModifiedDate` datetime DEFAULT NULL,
  `MerchantId` int(11) DEFAULT NULL,
  `P1` varchar(50) DEFAULT NULL,
  `P2` varchar(50) DEFAULT NULL,
  `P3` varchar(50) DEFAULT NULL,
  `P4` varchar(50) DEFAULT NULL,
  `SettlementCur` varchar(45) DEFAULT NULL,
  `ProcessingCharges` decimal(16,2) DEFAULT NULL,
  `ExpiryDurationType` varchar(250) DEFAULT NULL,
  `ExpiryDurationValue` int(11) DEFAULT NULL,
  `ExpiryDate` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_tblorderservice_tblBillingAddress` (`BillingAddressId`),
  KEY `FK_tblorderservice_tblCountryMgmt` (`ShippidCountry`),
  KEY `FK_tblorderservice_tblCountryStateMgmt` (`ShippidState`),
  KEY `FK_tblorderservice_tblOrderStatus` (`OrderStatusId`),
  KEY `FK_tblorderservice_aspnet_Users_idx` (`CustomerId`),
  CONSTRAINT `FK_tblorderservice_aspnet_Users` FOREIGN KEY (`CustomerId`) REFERENCES `tbluserinformation` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_tblorderservice_tblorderservicestatus` FOREIGN KEY (`OrderStatusId`) REFERENCES `tblorderservicestatus` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `tblorderserviceitem` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `OrderId` int(11) NOT NULL,
  `ProductId` int(11) DEFAULT NULL,
  `ProductName` varchar(250) DEFAULT NULL,
  `idOrderStatus` int(11) DEFAULT NULL,
  `Quantity` int(11) DEFAULT NULL,
  `UnitPriceInclTax` decimal(16,2) DEFAULT NULL,
  `UnitPriceExclTax` decimal(16,2) DEFAULT NULL,
  `PriceInclTax` decimal(16,2) DEFAULT NULL,
  `PriceExclTax` decimal(16,2) DEFAULT NULL,
  `DiscountAmountInclTax` decimal(16,2) DEFAULT NULL,
  `DiscountAmountExclTax` decimal(16,2) DEFAULT NULL,
  `OriginalProductCost` decimal(16,2) DEFAULT NULL,
  `AttributeDescription` varchar(500) DEFAULT NULL,
  `AttributesXml` longtext,
  `DownloadCount` int(11) DEFAULT NULL,
  `IsDownloadActivated` tinyint(1) DEFAULT NULL,
  `LicenseDownloadId` int(11) DEFAULT NULL,
  `ItemWeight` varchar(50) DEFAULT NULL,
  `UOM` varchar(50) DEFAULT NULL,
  `sku` varchar(25) DEFAULT NULL,
  `ModifiedDate` datetime DEFAULT NULL,
  `Attribute` varchar(500) DEFAULT NULL,
  `AttributeValue` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_tblorderserviceitem_tblOrderservice` (`OrderId`),
  KEY `FK_tblorderserviceitem_tblOrderStatus` (`idOrderStatus`),
  CONSTRAINT `FK_tblorderserviceitem_tblorderservice` FOREIGN KEY (`OrderId`) REFERENCES `tblorderservice` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_tblorderservicetime_tblorderservicestatus` FOREIGN KEY (`idOrderStatus`) REFERENCES `tblorderservicestatus` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;